### ISSUE TITLE
Airly network od unknown error

### ISSUE THREAD

**Issue by inetpr** [Nubzor/homebridge-airly-v2#5]
I’m getting an error while connecting to api
![9C584892-A217-401C-A9F7-7A37F066018F](https://user-images.githubusercontent.com/9152551/148375746-9a714386-a588-453a-b590-a14aa4a3f5c8.jpeg)
![9888AF4C-C510-4E70-B7F2-279EC74A8328](https://user-images.githubusercontent.com/9152551/148375759-3979d297-245a-4832-881d-a7529c828cd4.jpeg)

**Comment by Nubzor** [comment]
@inetpr, I improved the logging in the latest version of the app, please upgrade and share the detailed information.

Cheers.

**Comment by Nubzor** [comment]
Haven't heard much feedback since a while. Closing this one. Feel free to open another one if the errors persist.
