### ISSUE TITLE
API limit - change frequency

### ISSUE THREAD

**Issue by hpruszyn** [Nubzor/homebridge-airly-v2#6]
Hi, according to airly documentation there is a limit for api key: 100/day (https://developer.airly.org/en/docs#general.limits). I see in source code that we make request every 10 minutes which gives us 6/hour x 24 = 144 calls per day. Can you please change the code and make the period between calls longer (15minutes will be fine). Or make this value configurable.

**Comment by hpruszyn** [comment]
PR: https://github.com/Nubzor/homebridge-airly-v2/pull/7

**Comment by Nubzor** [comment]
@hpruszyn Make sense, thanks for rising.
